### ISSUE TITLE
Angular.js Hello World App

### ISSUE THREAD

**Issue by eshlefest** [eshlefest/atmospheres#3]

**Comment by vshl** [comment]
Here you go, its pretty simple to get angular running.. https://drive.google.com/open?id=0B4vJfp2Av2r8ckxOVFFLVkZtRDA&authuser=0

On other hand, I'm still going through the tutorials.. have to resume it this week.

I suggest we use the above google drive to drop our files and documents.. one place for everything related to the project. I created a directory for it.
